# Generated by Django 4.2.5 on 2023-09-16 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="classGoal",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="question",
        ),
    ]
